version: "3.8"
services:
  node1:
    build: .
    hostname: node1
    entrypoint: ["python", "chordpy/main.py", "node2", "5000"]
    environment:
    - "PYTHONUNBUFFERED=1"
  node2:
    build: .
    hostname: node2
    entrypoint: ["python", "chordpy/main.py", "node2", "5000"]
    environment:
    - "PYTHONUNBUFFERED=1"
  node3:
    build: .
    hostname: node3
    ports:
      - 5000:5000
    entrypoint: ["python", "chordpy/main.py", "node2", "5000"]
    environment:
    - "PYTHONUNBUFFERED=1"
